"""JeevesAgent — model-agnostic, MCP-native agent harness."""

from .agent import Agent
from .architecture import (
    AgentSession,
    Architecture,
    Dependencies,
    ReAct,
    resolve_architecture,
)
from .core import (
    AuditEntry,
    Budget,
    BudgetExceeded,
    BudgetStatus,
    CancelledByUser,
    CertifiedValue,
    ConfigError,
    Embedder,
    Episode,
    Event,
    EventKind,
    Fact,
    FreshnessError,
    HookHost,
    JeevesAgentError,
    LineageError,
    MCPError,
    Memory,
    MemoryBlock,
    MemoryStoreError,
    Message,
    Model,
    ModelChunk,
    PermissionDecision,
    PermissionDenied,
    Permissions,
    Role,
    RunResult,
    Runtime,
    RuntimeJournalError,
    RuntimeSession,
    Sandbox,
    SandboxError,
    Secrets,
    Span,
    Telemetry,
    ToolCall,
    ToolDef,
    ToolError,
    ToolEvent,
    ToolHost,
    ToolResult,
    Usage,
    deterministic_hash,
    new_id,
)
from .data import FreshnessPolicy, LineagePolicy
from .jeeves import JeevesConfig, JeevesGateway
from .mcp import MCPClient, MCPRegistry, MCPServerSpec
from .memory import (
    ChromaFactStore,
    ChromaMemory,
    CohereEmbedder,
    ConsolidationWorker,
    Consolidator,
    FactStore,
    HashEmbedder,
    InMemoryFactStore,
    InMemoryMemory,
    OpenAIEmbedder,
    PostgresFactStore,
    PostgresMemory,
    RedisFactStore,
    RedisMemory,
    SqliteFactStore,
    VectorMemory,
    VoyageEmbedder,
)
from .model import (
    AnthropicModel,
    EchoModel,
    LiteLLMModel,
    OpenAIModel,
    ScriptedModel,
    ScriptedTurn,
)
from .observability import NoTelemetry, OTelTelemetry
from .runtime import (
    InMemoryJournalStore,
    InProcRuntime,
    JournaledRuntime,
    JournalStore,
    PostgresJournalStore,
    PostgresRuntime,
    SqliteJournalStore,
    SqliteRuntime,
)
from .security import (
    AllowAll,
    AuditLog,
    FileAuditLog,
    FilesystemSandbox,
    HookRegistry,
    InMemoryAuditLog,
    Mode,
    NoSandbox,
    StandardPermissions,
    SubprocessSandbox,
)
from .tools import InProcessToolHost, Tool, tool

__version__ = "0.3.0.dev0"

__all__ = [
    "__version__",
    # public API
    "Agent",
    "Tool",
    "tool",
    "InProcessToolHost",
    # architecture
    "AgentSession",
    "Architecture",
    "Dependencies",
    "ReAct",
    "resolve_architecture",
    "AllowAll",
    "StandardPermissions",
    "HookRegistry",
    "Mode",
    "AnthropicModel",
    "EchoModel",
    "LiteLLMModel",
    "OpenAIModel",
    "ScriptedModel",
    "ScriptedTurn",
    "MCPClient",
    "MCPRegistry",
    "MCPServerSpec",
    "JeevesConfig",
    "JeevesGateway",
    "NoTelemetry",
    "OTelTelemetry",
    "InMemoryMemory",
    "VectorMemory",
    "ChromaMemory",
    "PostgresMemory",
    "RedisMemory",
    "HashEmbedder",
    "OpenAIEmbedder",
    "VoyageEmbedder",
    "CohereEmbedder",
    "Consolidator",
    "ConsolidationWorker",
    "FactStore",
    "InMemoryFactStore",
    "SqliteFactStore",
    "PostgresFactStore",
    "ChromaFactStore",
    "RedisFactStore",
    "AuditLog",
    "InMemoryAuditLog",
    "FileAuditLog",
    "NoSandbox",
    "FilesystemSandbox",
    "SubprocessSandbox",
    "FreshnessPolicy",
    "LineagePolicy",
    "InProcRuntime",
    "JournaledRuntime",
    "JournalStore",
    "InMemoryJournalStore",
    "SqliteJournalStore",
    "SqliteRuntime",
    "PostgresJournalStore",
    "PostgresRuntime",
    # types
    "AuditEntry",
    "BudgetStatus",
    "CertifiedValue",
    "Episode",
    "Event",
    "EventKind",
    "Fact",
    "MemoryBlock",
    "Message",
    "ModelChunk",
    "PermissionDecision",
    "Role",
    "RunResult",
    "Span",
    "ToolCall",
    "ToolDef",
    "ToolEvent",
    "ToolResult",
    "Usage",
    # protocols
    "Budget",
    "Embedder",
    "HookHost",
    "Memory",
    "Model",
    "Permissions",
    "Runtime",
    "RuntimeSession",
    "Sandbox",
    "Secrets",
    "Telemetry",
    "ToolHost",
    # errors
    "BudgetExceeded",
    "CancelledByUser",
    "ConfigError",
    "FreshnessError",
    "JeevesAgentError",
    "LineageError",
    "MCPError",
    "MemoryStoreError",
    "PermissionDenied",
    "RuntimeJournalError",
    "SandboxError",
    "ToolError",
    # ids
    "deterministic_hash",
    "new_id",
]
